### ISSUE TITLE
Release version 1.4.1

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#2122]
Instructions here - https://synfig-docs-dev.readthedocs.io/en/latest/common/release.html

- [x] Add latest translations from Transifex - https://github.com/synfig/synfig/pull/2125
- [x] Write ChangeLog - https://github.com/synfig/synfig/pull/2118
- [x] Test building of binary packages 
- [x] Test building of source tarballs: `./autobuild/synfigstudio-release.sh`
- [x] Add release commit and tag: `./version-release.sh`
- [x] Build binaries
- [x] Build source tarballs
- [x] Write release notes - https://github.com/synfig/synfig-docs/issues/25
- [x] Upload packages to GitHub, FossHub, Sf.net, Paddle
- [x] Publish announcement on website
- [x] Send announcement to subscribers in email list
- [x] Notify affected people in issues - https://github.com/synfig/synfig/projects/7
- [x] Publish announcement at OpenCollective
- [x] Move not-backported issues to next release (1.4.2) - https://github.com/synfig/synfig/projects/9

**Comment by morevnaproject** [comment]
"Test building of binary packages" - DONE
"Write ChangeLog " - DONE

**Comment by morevnaproject** [comment]
"Add latest translations from Transifex - #2125" - DONE

**Comment by morevnaproject** [comment]
"Build binaries" - DONE

**Comment by morevnaproject** [comment]
"Build source tarballs" - DONE

**Comment by morevnaproject** [comment]
"Write release notes" - DONE
"Upload packages to GitHub, FossHub, Sf.net, Paddle" -DONE
"Publish announcement on website" - DONE - https://www.synfig.org/2021/05/09/synfig-studio-1-4-1-released/

**Comment by morevnaproject** [comment]
Can someone help me with this task? ^__^ - "Notify affected people in issues" - https://github.com/synfig/synfig/projects/7

It's enough just to drop a comment like this on relevant issues - https://github.com/synfig/synfig/issues/1707#issuecomment-694686272

**Comment by rodolforg** [comment]
Should we close #1843 ?

**Comment by rodolforg** [comment]
> Can someone help me with this task? ^__^ - "Notify affected people in issues" - https://github.com/synfig/synfig/projects/7

Done

**Comment by morevnaproject** [comment]
> Done. I followed the commits from v1.4.0 until v1.4.1 in the v1.4.x branch

Awesome, thank you! ^__^

**Comment by morevnaproject** [comment]
> Should we close these issues?

I have closed them. I believe users can reopen if they still experience issues. ^__^

**Comment by morevnaproject** [comment]
"Send announcement to subscribers in email list" - DONE
"Publish announcement at OpenCollective" - DONE
