### ISSUE TITLE
Synfig crashes rendering to png sequences

### ISSUE THREAD

**Issue by Keyikedalube** [synfig/synfig#2204]
**Describe the bug**
Potential memory leak when rendering an animation file to png sequences.

**To Reproduce**
1. Create a 10s animation (or use this file [test.sif.zip](https://github.com/synfig/synfig/files/6757899/test.sif.zip))
2. Open task manager program
3. Render file to png sequences
4. Synfig will crash or if it doesn't will consume lots of computer memory (observe memory graph from task manager)

**Expected behavior**
Render to png sequences.

**Screenshots**
- **_CMake_**
![Screenshot_2021-07-03_10-23-06](https://user-images.githubusercontent.com/24214509/124344649-3227c300-dbf1-11eb-87ea-7cd88939320a.png)

- **_Autotools_**
![Screenshot_2021-07-03_10-33-15](https://user-images.githubusercontent.com/24214509/124344669-51265500-dbf1-11eb-8d41-5c267365af1f.png)

**System information:**
 - OS: Fedora Linux
 - OS version: 34
 - Commit ID: https://github.com/synfig/synfig/commit/4273435309266fa4181269fdb3e9cc454cf14337

**Additional comments**
Autotools build is OK. This is CMake only issue.

**Comment by Keyikedalube** [comment]
I just noticed Autotools writes to disk one-by-one while CMake writes to disk only after the whole specified file duration is rendered.

_Didn't look at the code, only observed it from the file manager program so the above statement of mine might be technically incorrect or limiting._

**Comment by rodolforg** [comment]
It seems to be two different Synfig Studio versions: look at current progress value position: in the top image is overlaying the progress bar; in the bottom one, it's above.

Could you check it?

**Comment by Keyikedalube** [comment]
_**Autotools (build commit id: f88027b)**_
![Screenshot_2021-07-13_08-03-19](https://user-images.githubusercontent.com/24214509/125381121-fb9c3600-e3b0-11eb-8dbb-ecde8f6c5a12.png)

**Comment by ice0** [comment]
@Keyikedalube can you show your render settings?

**Comment by Keyikedalube** [comment]
@ice0 

![Screenshot_2021-07-13_12-15-11](https://user-images.githubusercontent.com/24214509/125404277-146a1300-e3d4-11eb-81b3-06330fe552bc.png)
![Screenshot_2021-07-13_12-15-22](https://user-images.githubusercontent.com/24214509/125404303-1af88a80-e3d4-11eb-9e56-6b077de52093.png)
![Screenshot_2021-07-13_12-15-28](https://user-images.githubusercontent.com/24214509/125404326-20ee6b80-e3d4-11eb-984b-845b13e3f3b1.png)
![Screenshot_2021-07-13_12-15-33](https://user-images.githubusercontent.com/24214509/125404346-264bb600-e3d4-11eb-8954-1fec65a14635.png)

**Comment by ice0** [comment]
@Keyikedalube 
The `auto` target picks the first suitable renderer. So this can lead to different modules being used (maybe CMake build doesn't create one of them). Can you check it?
For `png` target, you can use `png`, `magick++` or `imagemagick` targets. 
I think one of them has this behavior.

**Comment by Keyikedalube** [comment]
Used `png` as target, you're right

![Screenshot_2021-07-13_13-08-56](https://user-images.githubusercontent.com/24214509/125411798-e2f54580-e3db-11eb-9cb3-5ff85dcf11be.png)

**Comment by coz-eduardo-hernandez** [comment]
I've been trying to debug this, turns out this bug was fixed in the past few months. It was present in a checkout from Sep 9, but today is gone.

That being said, under MSYS2 imagemagick fails, with the other png targets being fine. I built Synfig on Linux to be able to add debugging symbols (with debugging symbols it hits the limit of exported symbols even with CMake), but imagemagick works fine here, so I'll try to figure out another way to debug that.

However, shouldn't this issue be checked by @Keyikedalube to confirm if it can be closed?

**Comment by Keyikedalube** [comment]
So this was what caused this issue at the time:
- Built with CMake
- Rendered to png sequences using `Auto` in Target combobox

> Shouldn't this issue be checked by @Keyikedalube to confirm if it can be closed?

I'll check back on this today. But I suspect Synfig built with CMake should still reproduce this issue. No new commits/PR addresses (fixed) this issue so far.

**Comment by Keyikedalube** [comment]
On console, Synfig **Auto** detects file extension .png and uses **magick++** to render.

Sadly this issue is still reproducible for the Synfig version built with CMake. What really happens is rendered outputs are still kept in memory until the whole project file is fully rendered before being written to a hard disk.
