### ISSUE TITLE
Synfig 1.2 Running Skeleton Pluging Crashes  /in 64x Windows 7.

### ISSUE THREAD

**Issue by vuniverse** [synfig/synfig#334]
Synfig Crashes when loading skeleton plugin .
OS : Windows 7 64x 
Synfig Ver : synfigstudio-1.2.0-64bit.exe

CONSOLE : 
synfig(5776) [15:19:20] error: Standard Exception: Document not well-formed.
Line 1, column 1 (fatal):
Extra content at the end of the document

Crash Log : 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	synfigstudio.exe
  Application Version:	0.0.0.0
  Application Timestamp:	585e6934
  Fault Module Name:	libsynfigapp-0.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	585e6874
  Exception Code:	c0000005
  Exception Offset:	00000000001663ce
  OS Version:	6.1.7601.2.1.0.256.1

**Comment by caryoscelus** [comment]
Probably was fixed by <https://github.com/synfig/synfig/commit/f64bdfa950fad5fc9fd9bf9c0907a94c78926364>. Try running plugin with .sif (not .sifz) document.

**Comment by vuniverse** [comment]
Hi caryoscelus 
There is not a folder called synfig-studio/src/synfigapp/ and file called pluginmanager.cpp file in my synfig app folders. That is what i read from f64bdfa.
I have only synfig/plugin folders.

**Comment by caryoscelus** [comment]
There is no point in reading patches if you don't build synfig from source. I just pointed that it is probably already fixed in that commit.

**Comment by vuniverse** [comment]
Which version i should use ? Did not fixed version released yet ?

**Comment by caryoscelus** [comment]
No. You can build it yourself if you want, though.

But i don't think skeleton plugin has any use - you can just add skeleton layer instead.

And if you really must use plugins in pre-built version, as i said, try using it with .sif.

**Comment by vuniverse** [comment]
Oh sorry ..I thought it was not possible to use skeleton without that plugin.  It is my first time with synfig. Thank you very much.

**Comment by caryoscelus** [comment]
No problem :)

**Comment by morevnaproject** [comment]
@vuniverse The fix now shipped with latest development builds - https://morevnaproject.org/2017/04/23/synfig-studio-1-3-2-development/
