### ISSUE TITLE
Forums down

### ISSUE THREAD

**Issue by millerthegorilla** [synfig/synfig#681]
The forums are down, and I am unable to access any of the advice presented there.  I'd particularly like to be able to import multiple pngs for instance.

Just to let you know.  Many thanks for all your work!

**Comment by millerthegorilla** [comment]
Oh, and would you mind providing sha256 checksums for your downloads please.  Md5sums are not sufficiently safe from in-file-transfer hacking, at least as I understand it.
Thanks

**Comment by FadhilKwan** [comment]
sorry to bring this up again, but it seems like the forum is going down (again)....
the error says "Site Unreachable"......
is everyone affected or is it just me?

**Comment by morevnaproject** [comment]
@FadhilKwan Thank you for notification! Fixed now. ^__^

**Comment by FadhilKwan** [comment]
Thank you very much! 😄

**Comment by FadhilKwan** [comment]
ummmm..... this is awkward....
sorry to bring this up again (and yes, it's the second time already), but it seems like the forum is going down (again)....
still the same error: "Site Unreachable"

it has happened from around 12 hours ago, but i decided to wait first in case it will get resolved at one point, although it looks like the error still persists
(._.)

**Comment by AnishGG** [comment]
> it seems like the forum is going down

It is working fine for me now. Could you check again?

**Comment by FadhilKwan** [comment]
> > it seems like the forum is going down
> 
> It is working fine for me now. Could you check again?

alright it's working fine. the problem was from my internet provider:
in short, i have to use VPN to access it,
this is very weird, because it was woking fine without the need to use VPN yesterday. (o_o)

Anyway, thanks for the suggestion! (^-^)
