### ISSUE TITLE
Outline render issue

### ISSUE THREAD

**Issue by morevnaproject** [synfig/synfig#698]
**Synfig version & platform**:
Synfig master branch, commit id 25d55580b

**Issue description**:
Sample test file - https://github.com/synfig/synfig-tests-regressions/blob/master/rendering/sources/layers/outline/outline-looped-cusps-off.sif

Render result:
![screenshot_001](https://user-images.githubusercontent.com/332868/50625051-e2041300-0f57-11e9-9660-e980190700b8.png)

Expected result  (v 1.0.2):
![screenshot_002](https://user-images.githubusercontent.com/332868/50625077-1a0b5600-0f58-11e9-9d60-dcf9f2a330ed.png)

**Comment by morevnaproject** [comment]
See also comment here regarding cusps - https://github.com/synfig/synfig/issues/314#issuecomment-429726173

**Comment by morevnaproject** [comment]
@blackwarthog Any progress on this? ^__^

**Comment by blackwarthog** [comment]
fixed

**Comment by morevnaproject** [comment]
@blackwarthog I have tested the latest version and the result is still different -

Master branch, commit 4b7e52ad779da4f179d74f63dc695c916a95cd5f:

![screenshot_002](https://user-images.githubusercontent.com/332868/51364430-aac46300-1b0e-11e9-9164-a7b7f22eb669.png)

**Comment by Kinoblit** [comment]
I'd like to confirm that this is still happening (built off of `7ef36d286be8a83e4415670835b6b62456e21b1a`).

![bad_loop](https://user-images.githubusercontent.com/49011417/55270514-de8dd880-5275-11e9-9576-32578047b643.png)

**Comment by ebarranco** [comment]
This seems fixed now, thanks!
