### ISSUE TITLE
Failed to build on macOS Mojave

### ISSUE THREAD

**Issue by AnishGG** [synfig/synfig#794]
**Platform**:
macOS Mojave
Version: 10.14.3
Macbook Pro(15 inch, 2018)

**Synfig version**
Commit: [7ef36d2](https://github.com/synfig/synfig/commit/7ef36d286be8a83e4415670835b6b62456e21b1a) (latest)

**Issue description**:
`1-setup-osx-brew.sh` ran without error.
`2-build-production.sh` fails to build with this error: 
```checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool```

**Comment by morevnaproject** [comment]
Hmm... that's weird. As I read on https://github.com/Homebrew/linuxbrew-core/issues/4499 -

> On OS X, XML::Parser is provided by the operating system.

**Comment by AnishGG** [comment]
One solution: Check for `XML::Parser` in `1-setup-osx-brew.sh`, if not present then install it. Is this fine @morevnaproject ?
I will make the necessary changes if the above is ok.

**Comment by AnishGG** [comment]
I could follow this [link](http://ripary.com/bundle-xml.html) to install XML::Parser?

**Comment by morevnaproject** [comment]
> I could follow this link to install XML::Parser?

I'm afraid this can be too intrusive and might break your system.

Can you please run ```1-setup-osx-brew.sh``` again and post its full output here?

**Comment by AnishGG** [comment]
Here is the output after running `1-setup-osx-brew.sh` again.
`Checking adwaita-icon-theme...
Checking autoconf...
Checking automake...
Checking ccache...
Checking libtool...
Checking intltool...
 Checking imagemagick...
Checking gettext...
Checking pkg-config...
Checking glibmm...
Checking libxml++...
Checking cairo...
Checking fftw...
Checking pango...
Checking mlt...
Checking boost...
Checking gtkmm3...
Checking sdl2...
Checking sdl2_mixer...
`

All the above `Checking` are preceded by line breaks. For some reason I am not able to put line breaks inside code block here.

**Comment by morevnaproject** [comment]
> For some reason I am not able to put line breaks inside code block here

I have fixed that in your comment. ^__^

Okay, now please post a full output of ```2-build-production.sh```. Since it might be long, you might want to use https://gist.github.com/ for that.

**Comment by AnishGG** [comment]
> Okay, now please post a full output of `2-build-production.sh`. Since it might be long, you might want to use https://gist.github.com/ for that.

Here is the output.
[logs.txt](https://gist.github.com/AnishGG/80c81a3f5ce6a3955132205f8958c466)

**Comment by morevnaproject** [comment]
Okay. Now, please give me content of ```~/Repos/anish/synfig/_production/synfig-core/config.log```.

**Comment by AnishGG** [comment]
> Okay. Now, please give me content of `~/Repos/anish/synfig/_production/synfig-core/config.log`.

Here it is. [config.log](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)

**Comment by morevnaproject** [comment]
Okay, here is what I see in your output:

```
configure:20903: checking for perl
configure:20921: found /usr/local/bin/perl
configure:20933: result: /usr/local/bin/perl
configure:20944: checking for perl >= 5.8.1
configure:20951: result: 5.28.1
configure:20955: checking for XML::Parser
configure:20961: error: XML::Parser perl module is required for intltool

```

And here are lines from ```config.log``` on my OSX system:
```
configure:20903: checking for perl
configure:20921: found /usr/bin/perl
configure:20933: result: /usr/bin/perl
configure:20944: checking for perl >= 5.8.1
configure:20951: result: 5.16.2
configure:20955: checking for XML::Parser
configure:20958: result: ok
```

Notice, your perl installation is found in **/usr/local/bin**. While in my case perl found in **/usr/bin** (system one).

So, I suspect you have custom installation of perl, which doesn't provides XML::Parser.

Please execute following commands and post its output here:

```
ls -al /usr/local/bin/perl
```

```
ls -al /usr/bin/perl
```

**Comment by AnishGG** [comment]
Here are the outputs
`ls -al /usr/local/bin/perl`
 -> 
`lrwxr-xr-x 1 mohsin admin 30 Jan 3 01:17 /usr/local/bin/perl -> ../Cellar/perl/5.28.1/bin/perl`
and
`ls -al /usr/bin/perl`
->
`-rwxr-xr-x 1 root wheel 66608 Nov 30 11:24 /usr/bin/perl`

**Comment by morevnaproject** [comment]
> lrwxr-xr-x 1 mohsin admin 30 Jan 3 01:17 /usr/local/bin/perl -> ../Cellar/perl/5.28.1/bin/perl

So, you have a perl package installed via homebrew. Can you try to uninstall it?

```brew uninstall perl```

**Comment by AnishGG** [comment]
> Can you try to uninstall it?

I tried to uninstall it, but then I realized that it is a dependency for `vim`. Is there any other way to achieve the same?
This is the output for `brew uninstall perl`:

`Error: Refusing to uninstall /usr/local/Cellar/perl/5.28.1`
`because it is required by vim, which is currently installed.`
`You can override this and force removal with:`
 ` brew uninstall --ignore-dependencies perl`

**Comment by AnishGG** [comment]
From the above, I understand that I have two perl packages installed on my machine. Is there any way that it detects the system installed version, and not the custom version of perl installed from homebrew?

**Comment by ice0** [comment]
Here i see 2 variants:
- 1. switch to system version of perl;
or
- 2. install XML::LibXML for brew perl (brew install libxml2)

**Comment by morevnaproject** [comment]
> I tried to uninstall it, but then I realized that it is a dependency for vim. Is there any other way to achieve the same?

Then I suggest to try to uninstall "perl" and "vim". ^__^
```
brew uninstall vim
brew uninstall perl
```

> From the above, I understand that I have two perl packages installed on my machine. 

Exactly. ^__^

> Is there any way that it detects the system installed version, and not the custom version of perl installed from homebrew?

First, I suggest switch to system Perl by removing brew's installation of Perl. If that will fix the problem, then we can dig further and think how to handle case with two perl installations. But, if the issue **will not** go away after removing brew's Perl, then this will indicate that the problem is in some other place.

> 2. install XML::LibXML for brew perl (brew install libxml2)

This will not work, as ```libxml2``` doesn't provides Perl's ```XML::LibXML```. ^__^

**Comment by ice0** [comment]
> This will not work, as libxml2 doesn't provides Perl's XML::LibXML. ^__^

Ok then it can be installed from cpan:

```
perl -eshell -MCPAN
install XML::LibXML
```

Not sure if this is the right way, but it might be worth a try.

**Comment by AnishGG** [comment]
> Then I suggest to try to uninstall "perl" and "vim".

As this Mac is not my personal machine, I won't be able to uninstall vim. :slightly_frowning_face: 


> Ok then it can be installed from cpan:
> 
> ```
> perl -eshell -MCPAN
> install XML::LibXML
> ```
> 
> Not sure if this is the right way, but it might be worth a try.

But sure, I will give this a try and update here what happens.
Thanks

**Comment by AnishGG** [comment]
> > This will not work, as libxml2 doesn't provides Perl's XML::LibXML. ^__^
> 
> Ok then it can be installed from cpan:
> 
> ```
> perl -eshell -MCPAN
> install XML::LibXML
> ```
> 
> Not sure if this is the right way, but it might be worth a try.

So, I tried executing the given instructions, but then this installation also failed with the following output. 
[logs.txt](https://gist.github.com/AnishGG/6d6d9c2755d3e91810fd1b3a60661174 ).
I have no clue how to proceed further with this. Please guide me what could be done here. 
Thank you

**Comment by morevnaproject** [comment]
@AnishGG I understand the situation. I also understand that the same might happen to other users, who want to have perl in their homebrew install.

As a possible solution, we can use different location for Synfig's homebrew installation - https://github.com/Homebrew/brew/blob/664d0c67d5947605c914c4c56ebcfaa80cb6eca0/docs/Installation.md#alternative-installs

**Comment by morevnaproject** [comment]
> As a possible solution, we can use different location for Synfig's homebrew installation - https://github.com/Homebrew/brew/blob/664d0c67d5947605c914c4c56ebcfaa80cb6eca0/docs/Installation.md#alternative-installs

Oh, no - this wouldn't work. Two installations of HomeBrew will conflict because they install files of python3 into ```/Library```.

But I have one simple idea how to force usage of system perl...

**Comment by AnishGG** [comment]
> But I have one simple idea how to force usage of system perl...

🙂  Alright, I am curious. How do we do that?

**Comment by morevnaproject** [comment]
@AnishGG I have made changes. Please fetch latest commit and try to build again. ^__^

**Comment by AnishGG** [comment]
> @AnishGG I have made changes. Please fetch latest commit and try to build again. ^__^

I will test it as soon as I get the machine and update the results here.
Thank you!

**Comment by morevnaproject** [comment]
I have pushed one more commit just now (d309b150488766079). Please make sure to get it as well (without it nothing will work). ^__^

**Comment by AnishGG** [comment]
@morevnaproject, This fix worked like a charm 😃. 
I guess this closes the issue. 
But now I am getting this error:
`checking for glibmm-2.4 >= 2.24.2... configure: error:  ** You need to install glibmm-2.4 version 2.24.2 or higher.`
This issue was also mentioned by @amanbora at #803.

**Comment by morevnaproject** [comment]
> But now I am getting this error:

Well, let's keep investigating. ^__^
Please give me content of ```~/Repos/anish/synfig/_production/synfig-core/config.log``` again.

**Comment by AnishGG** [comment]
> Please give me content of `~/Repos/anish/synfig/_production/synfig-core/config.log` again.

I have updated the previous gist. [config.log](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)

**Comment by morevnaproject** [comment]
@AnishGG  Please execute those two commands and paste their output here:

```
pkg-config --print-errors --cflags glibmm-2.4
```

```
ls /usr/local/lib/pkgconfig/glibmm*
```

**Comment by AnishGG** [comment]
Here are the outputs:
> pkg-config --print-errors --cflags glibmm-2.4

https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd


> ls /usr/local/lib/pkgconfig/glibmm*

`/usr/local/lib/pkgconfig/glibmm-2.4.pc`

**Comment by morevnaproject** [comment]
> Package libffi was not found in the pkg-config search path.

How interesting! Please give me output of this commands then:

```brew info libffi```

```ls /usr/local/lib/pkgconfig/libffi*```

**Comment by AnishGG** [comment]
Corresponding outputs:
> brew info libffi

https://gist.github.com/AnishGG/7fb79337c7a0fe2936956aa85cbd7b09


> ls /usr/local/lib/pkgconfig/libffi*

`zsh: no matches found: /usr/local/lib/pkgconfig/libffi*`

**Comment by morevnaproject** [comment]
We're getting closer to solution. Please give me output of this:

```PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" pkg-config --print-errors --cflags glibmm-2.4```

**Comment by AnishGG** [comment]
Here we go:
> PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" pkg-config --print-errors --cflags glibmm-2.4

https://gist.github.com/AnishGG/6fa629bb438258b43a0438697e21be57

**Comment by morevnaproject** [comment]
Cool! I have pushed fix to master branch (4738a94ea9fbebe1c225b2b61ae0dfb116afe2a7). Please check if compilation works for you now. ^__^

**Comment by AnishGG** [comment]
> Cool! I have pushed fix to master branch ([4738a94](https://github.com/synfig/synfig/commit/4738a94ea9fbebe1c225b2b61ae0dfb116afe2a7)). Please check if compilation works for you now. ^__^

I guess this fixed the glibmm issue :smile: , but the build still fails when proceeded. 
I am pasting the error here:
https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd

I have updated the config.log accordingly: [config.log](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)

**Comment by morevnaproject** [comment]
Acknowledged, I am thinking on solution. In the meantime, can you please provide more lines of error output? ^__^

**Comment by AnishGG** [comment]
> can you please provide more lines of error output?

These are the final lines of error output. Do you mean the output lines before this?

**Comment by AnishGG** [comment]
> In the meantime, can you please provide more lines of error output?

@morevnaproject 
Here is the full output after running 2-build-production:
https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd

**Comment by morevnaproject** [comment]
> Here is the full output after running 2-build-production:
> https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd

For some reason I do not see last lines with errors in this gist. ^__^"

**Comment by AnishGG** [comment]
> For some reason I do not see last lines with errors in this gist.

The last lines with errors are these only [(link)](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd/9b9adae4595e369449f882304c51a9ba2661d145). There was no output generated after this.


> Here is the full output after running 2-build-production:
> https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd

The output in this link is truncated. You might be able to see the last lines in the raw output[(link)](https://gist.githubusercontent.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd/raw/b1da680fd4f8fb927946909256ff66001e7a18e4/log_output.txt) section.

**Comment by morevnaproject** [comment]
I have read this thread - https://github.com/Microsoft/LightGBM/issues/3 - and it looks like you have "clang" compiler set as default instead of "gcc".

Please give me an output of those commands:

```brew info gcc```

```ls -al /usr/local/bin/gcc*```

**Comment by morevnaproject** [comment]
And also those commands:

```ls -al `which g++` ```

```ls -al /usr/local/bin/g++*```

**Comment by AnishGG** [comment]
> I have read this thread - [Microsoft/LightGBM#3](https://github.com/Microsoft/LightGBM/issues/3) - and it looks like you have "clang" compiler set as default instead of "gcc".

I see, I will also have a look at it.
Here are the outputs of the asked commands:


> brew info gcc

https://gist.github.com/AnishGG/792fda9857bf390177f91131d912d8d6

> ls -al /usr/local/bin/gcc*

https://gist.github.com/AnishGG/6952b39e00935f77319003e920c583ef

> ls -al `which g++`

`-rwxr-xr-x  1 root  wheel  18288 Feb  5 10:58 /usr/bin/g++`

> ls -al /usr/local/bin/g++*

`lrwxr-xr-x  1 mohsin  admin  29 Mar 26 19:24 /usr/local/bin/g++-8 -> ../Cellar/gcc/8.3.0/bin/g++-8`

**Comment by morevnaproject** [comment]
@AnishGG Thank you! Please try to build Synfig by executing the following commands:

```
cd ~/Repos/anish/synfig/
CXX=/usr/local/bin/g++-8 ./2-build-production.sh
```

**Comment by AnishGG** [comment]
> @AnishGG Thank you! Please try to build Synfig by executing the following commands:
> 
> ```
> cd ~/Repos/anish/synfig/
> CXX=/usr/local/bin/g++-8 ./2-build-production.sh
> ```

@morevnaproject, I tried building Synfig using the given commands. It fixed the previous issue of "clang" being the default compiler. But again there is some another issue.
I have updated the config.log. [(link)](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)
Here are the terminal logs after executing the given commands(2-build-production.sh) [(link)](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd).

P.S.: These errors seem never ending :'(. I hope a successful build after fixing this.

**Comment by morevnaproject** [comment]
@AnishGG Can you please give me last lines of output? The gist at https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd doesn't give me last lines, so I do not see error message.

**Comment by AnishGG** [comment]
> @AnishGG Can you please give me last lines of output? The gist at https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd doesn't give me last lines, so I do not see error message.

I will clarify this. When we open this link, it shows the following:
![truncated](https://user-images.githubusercontent.com/30872212/56090610-0a3dcf00-5ec2-11e9-8862-b612eb9f39c3.PNG)
This might be the reason you are not able to see the full output. Here we need to see the raw output which can be accessed by clicking on `Raw` or `view the full file`. 
Here is the link to it: https://gist.githubusercontent.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd/raw/c3af3464aaca67bfe071a9784d659f04b39bdb03/log_output.txt
Hope this helps 🙂

**Comment by morevnaproject** [comment]
Oh, my bad. I hasn't paid attention to this link. ^__^"  Thank you! ^__^

**Comment by morevnaproject** [comment]
@AnishGG Please give me an output of ```brew info llvm```.

**Comment by AnishGG** [comment]
> @AnishGG Please give me an output of `brew info llvm`.

Here it is:
<pre>
<code>
llvm: stable 8.0.0 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
https://llvm.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb
==> Dependencies
Build: cmake ✘
Required: libffi ✔
==> Requirements
Build: xcode ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

==> Analytics
install: 19,903 (30 days), 42,427 (90 days), 164,582 (365 days)
install_on_request: 15,163 (30 days), 33,010 (90 days), 128,149 (365 days)
build_error: 0 (30 days)
</code>
</pre>

**Comment by morevnaproject** [comment]
@AnishGG Thank you! I have pushed commit 36eac61006ec9a096243f1aba242028b644b8947 which should fix the issue.

**Comment by AnishGG** [comment]
@morevnaproject, On the latest commit I ran the following command
<pre><code>cd ~/Repos/anish/synfig/
CXX=/usr/local/bin/g++-8 ./2-build-production.sh</code></pre>

But, it still errored. I think it is still giving the previous error. 
Here I updated the config.log([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)) and terminal output.([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd))

One notable difference in config.log: 
`ld: warning: directory not found for option '-L/usr/local/opt/llvm/lib'`

**Comment by morevnaproject** [comment]
Oh, I see. I haven't noticed from your previous comment that llvm is actually not installed.

Please give me an output of ```brew info libomp```.

**Comment by AnishGG** [comment]
> brew info libomp

<pre><code>libomp: stable 7.0.0 (bottled)
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/usr/local/Cellar/libomp/7.0.0 (12 files, 1.2MB) *
  Poured from bottle on 2019-03-26 at 19:21:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libomp.rb
==> Dependencies
Build: cmake ✘
==> Requirements
Required: macOS >= 10.10 ✔
==> Analytics
install: 39,050 (30 days), 143,167 (90 days), 179,631 (365 days)
install_on_request: 4,824 (30 days), 13,822 (90 days), 29,787 (365 days)
build_error: 0 (30 days)</code></pre>

**Comment by morevnaproject** [comment]
Now, please give me an output of this:

```ls "$(brew --prefix libomp)/lib"```

**Comment by AnishGG** [comment]
> ls "$(brew --prefix libomp)/lib"

`libgomp.a      libgomp.dylib  libiomp5.a     libiomp5.dylib libomp.a       libomp.dylib`

**Comment by morevnaproject** [comment]
Committed a fix. Please try to build with the latest master again. ^__^

**Comment by AnishGG** [comment]
I guess you made an error in the last commit. The config.log differed here:
` ld: warning: directory not found for option '-L"/usr/local/opt/libomp/lib"'`
There seems to be an extra `"` after `L` in the commit.
The build fails with the following error:
config.log([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)) and terminal output([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd))

**Comment by morevnaproject** [comment]
You right! Fixed now. Please try again. ^__^

**Comment by AnishGG** [comment]
@morevnaproject, Build is still failing. I am not sure if the previous error is fixed.
Please have a look at it whenever you got time.
terminal output([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd))
config.log([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4))

**Comment by morevnaproject** [comment]
This is another problem. ^__^ Please give me an output of:

```
brew info libtool
brew --prefix libtool
ls $(brew --prefix libtool)
```

Also, according to https://github.com/Homebrew/legacy-homebrew/issues/32791#issuecomment-57528641 executing this might fix the issue:

```
brew unlink libtool && brew link libtool
```

**Comment by AnishGG** [comment]
Here are the asked outputs.
> brew info libtool

<pre><code>libtool: stable 2.4.6 (bottled)
Generic library support script
https://www.gnu.org/software/libtool/
/usr/local/Cellar/libtool/2.4.6_1 (71 files, 3.7MB) *
  Poured from bottle on 2019-03-25 at 01:21:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtool.rb
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Analytics
install: 97,157 (30 days), 287,918 (90 days), 1,089,504 (365 days)
install_on_request: 21,076 (30 days), 62,858 (90 days), 259,640 (365 days)
build_error: 0 (30 days)</code></pre>

> brew --prefix libtool

`/usr/local/opt/libtool`

> ls $(brew --prefix libtool)

<pre><code>AUTHORS              ChangeLog            NEWS                 TODO                 include              share
COPYING              INSTALL_RECEIPT.json README               bin                  lib</code></pre>
I ran this command also:

> brew unlink libtool && brew link libtool

and then tried making Synfig but build fails with same output. Hence there is no change in config.log and terminal output.

**Comment by morevnaproject** [comment]
Okay, please give me an output for one more command:

```
ls $(brew --prefix libtool)/lib
```

**Comment by AnishGG** [comment]
Here it is:
> ls $(brew --prefix libtool)/lib

`libltdl.7.dylib libltdl.a       libltdl.dylib`

**Comment by morevnaproject** [comment]
Pushed one more fix - d8e465235e2f0dac913acafaf941e92c5b2c2aa0. Please test again. ^__^

**Comment by AnishGG** [comment]
@morevnaproject, So I tested with the new commit. I guess this error is fixed :slightly_smiling_face:, but something related to this error has poped up. 
I have updated the config.log([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)) and terminal output([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd)).
Please have a look whenever you have time.
Thanks

**Comment by AnishGG** [comment]
This error seems to be related to #ucbrise/clipper/issues/300 and I guess this([link](https://github.com/ucbrise/clipper/issues/300#issuecomment-391031197)) might be a fix to it. 
Hope this helps ^_^

**Comment by morevnaproject** [comment]
There is something totally wrong here - I still see traces of clang.

Okay, let's try something different.

Can you install brew's llvm package on this OSX system? Using this command:
```
brew install llvm
```

After that, please try to remove **"~/Repos/anish/synfig/_production/"**:

```
rm -rf ~/Repos/anish/synfig/_production/
```

...and then run build script (without **"CXX=/usr/local/bin/g++-8"** prefix):

```
./2-build-production.sh
```

**Comment by AnishGG** [comment]
> brew install llvm

Successful


> rm -rf ~/Repos/anish/synfig/_production/

Done

> ./2-build-production.sh

Build fails with `clang: error: unsupported option '-fopenmp'`.  I guess we faced this same issue before using `CXX=/usr/local/bin/g++-8` command also.
Anyways here are the updated config.log([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4)) and terminal output([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd)).
Thanks for helping!

**Comment by morevnaproject** [comment]
Sorry, for not being active with this issue. I am considering to fins Mojave instance and try to build Synfig there myself. ^__^"

In the meantime, I have found this article - https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

So, can you please run last command in the following way:

```
CXXFLAGS="-Xpreprocessor -fopenmp -lomp -I$(brew --prefix libomp)/include -L$(brew --prefix libomp)/lib $CXXFLAGS" ./2-build-production.sh
```

Does this changes anything?

**Comment by AnishGG** [comment]
> In the meantime, I have found this article - https://iscinumpy.gitlab.io/post/omp-on-high-sierra/
> 
> So, can you please run last command in the following way:
> 
> ```
> CXXFLAGS="-Xpreprocessor -fopenmp -lomp -I$(brew --prefix libomp)/include -L$(brew --prefix libomp)/lib $CXXFLAGS" ./2-build-production.sh
> ```
> 
> Does this changes anything?

Will post the output as soon as I get the access to the machine.

**Comment by AnishGG** [comment]
@morevnaproject, It fails to build still. I have updated the corresponding files:
config.log ([link](https://gist.github.com/AnishGG/7b0d1c1c9e2f157506cb01b57f3810a4))
terminal output ([link](https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd))

**Comment by morevnaproject** [comment]
Hi! I checked the terminal output (https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd) and it looks truncated. Am I missing something again? ^__^

**Comment by AnishGG** [comment]
> Hi! I checked the terminal output (https://gist.github.com/AnishGG/20801701a9eb8cf61cadd1fdd0d032fd) and it looks truncated. Am I missing something again? ^__^

I guess, I missed something while copying. Will update this file and ping here.

**Comment by markgalassi** [comment]
was any progress ever made on this?  I'm running in to annoying libtool behavior on MacOS where it introduces -fopenmp (even though that was never in the link flags) and then fails with the same message you are getting, since -fopenmp was never meant to be a link option. I'd love to see if you ever fixed your failure.

**Comment by ice0** [comment]
As far as I remember, `-fopenmp` was added by the ImageMagick library.
So a few thoughts:
1) Install gcc (brew) and use it to build. It supports `openmp` out of the box. Clang on MacOS is not :(
2) Fix the ImageMagick .pc file and remove this flag manually. (this is what I want to do on Travis-CI).

**Comment by morevnaproject** [comment]
There is option 3: Do not use brew's package and re-compile ImageMagick by hand? ^__^

**Comment by ice0** [comment]
Currently this problem can be solved by using CMake on macOS systems. So I close this issue now. 

P.S. If someone can't use CMake for some reason on MacOS, please comment here.

**Comment by morevnaproject** [comment]
> As far as I remember, `-fopenmp` was added by the ImageMagick library

From [this link](https://superuser.com/questions/324980/how-do-you-re-install-a-package-with-homebrew-mac/575255) I found that it is possible to re-install ImageMagick without OpenMP:

```
brew install imagemagick --disable-openmp --force
```

@ice0 Should we reopen this issue and modify our build scripts? ^__^

**Comment by ice0** [comment]
@morevnaproject Sure.

**Comment by ryandesign** [comment]
> `checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool`

This is [an intltool bug](https://bugs.launchpad.net/intltool/+bug/1197875). A configure script built with intltool.m4 will check for perl and will check if that perl has XML::Parser. It is unnecessary and erroneous for it to do this because the perl that is found is not necessarily the perl that xmlparser has been configured to use. In MacPorts, we fix this by [patching intltool.m4](https://github.com/macports/macports-ports/blob/9a6b69cab4db44687ee4bd00f45e8f230ddc9f98/textproc/intltool/files/patch-remove-intltool-perl-hack.diff) to remove the offending check. Affected software can have its configure script rebuilt with the corrected intltool.m4 by running `autoreconf`. Or, the affected configure script can be patched directly with a patch such as [this one](https://github.com/macports/macports-ports/blob/4a58212ee2cc108529b61016190424f8080552be/xfce/libxfce4ui/files/remove-intltool-perl-hack.diff). Unfortunately, since its developers have never responded to the intltool bug since it was filed in 2013 I assume the developers have ceased to exist and this bug will never be fixed.
